version: '2.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/local/nginx/certs:/etc/nginx/certs
#     - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/local/nginx/certs:/etc/nginx/certs:rw

networks:
    default:
        external:
            name: knutech_main